development:
  FB_PAGE_KEY: 'EAAB2lF1nr5ABAIZCIU1Q1IqZBI3xeI7OKxULrZCWm5GOpf2AyZCrtR52oLiBOOH2MNVjAtAsfJY1GWnSVVjySlycZBZAm32MydPEPyZAZAt0xz2cd35r9y26PNVCqOAGxht54cXbwZCRN8onHR1HIghufKaXyp2leg0pLlqetw8IqCqzh2kPDCJAu'
  FB_SECRET_PASS: '8337f0cda0ab09701c14de8fa192c45c'

staging:
  FB_PAGE_KEY: 'EAAB2lF1nr5ABAIZCIU1Q1IqZBI3xeI7OKxULrZCWm5GOpf2AyZCrtR52oLiBOOH2MNVjAtAsfJY1GWnSVVjySlycZBZAm32MydPEPyZAZAt0xz2cd35r9y26PNVCqOAGxht54cXbwZCRN8onHR1HIghufKaXyp2leg0pLlqetw8IqCqzh2kPDCJAu'
  FB_SECRET_PASS: '8337f0cda0ab09701c14de8fa192c45c'

production:
  FB_PAGE_KEY: 'EAAB2lF1nr5ABAIZCIU1Q1IqZBI3xeI7OKxULrZCWm5GOpf2AyZCrtR52oLiBOOH2MNVjAtAsfJY1GWnSVVjySlycZBZAm32MydPEPyZAZAt0xz2cd35r9y26PNVCqOAGxht54cXbwZCRN8onHR1HIghufKaXyp2leg0pLlqetw8IqCqzh2kPDCJAu'
  FB_SECRET_PASS: '8337f0cda0ab09701c14de8fa192c45c'

